//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMovies.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public Movie()
        {
            this.MovieGenres = new HashSet<MovieGenre>();
            this.Watches = new HashSet<Watch>();
        }
    
        public int MovieId { get; set; }
        public string OriginalName { get; set; }
        public string EnglishName { get; set; }
        public string RussianName { get; set; }
        public string OverView { get; set; }
        public int RunTime { get; set; }
        public string Poster { get; set; }
        public string ImdbId { get; set; }
        public int Rating { get; set; }
        public int RevCount { get; set; }
        public int Year { get; set; }
    
        public virtual ICollection<MovieGenre> MovieGenres { get; set; }
        public virtual ICollection<Watch> Watches { get; set; }
    }
}
