//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMovies.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Watches = new HashSet<Watch>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Avatara { get; set; }
        public int TimeWasted { get; set; }
    
        public virtual ICollection<Watch> Watches { get; set; }
    }
}
