//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMovies.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Watch
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int MovieId { get; set; }
        public Nullable<int> Rate { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
